#[cfg(test)]
mod cw_token_add_remove_margin_tests;
mod cw_token_liquidation_frontrun_hack_tests;
mod cw_token_liquidation_tests;
mod cw_token_pay_funding_tests;
mod cw_token_position_fee_tests;
mod fee_calculation_tests;
mod fluctuation_tests;
mod margin_engine_tests;
mod margin_ratio_tests;
mod native_token_add_remove_margin_tests;
mod native_token_liquidation_tests;
mod native_token_position_fee_tests;
mod open_notional_tests;
mod pausable_tests;
mod personal_position_tests;
mod position_liquidation_tests;
mod position_tests;
mod tests;
